### PR TITLE
Improve API for NPM Package

### PR DESCRIPTION
**Pull request by paulstatezny**
## Improve API for NPM Package

It'd be nice if instead of `require('synapse-common/http/auth-gateway')` and `require('synapse-common/store/match-media')` we could just do:

```JS
require('synapse-common').MatchMediaStore
require('synapse-common').AuthGateway
```

### Acceptance Criteria
1. Index file exists with references to 

### Tasks
- Create index file, reference it in package.json

### Additional Notes
- I'm not certain if we could still require things by path, so this might be BC breaking.

### CODE REVIEW

**Comment by paulstatezny** [comment]
:sunny: :arrow_up:

**Comment by paulstatezny** [comment]
:star:

**Comment by paulstatezny** [comment]
I tested this on a project and it works.

**Comment by tdboone** [comment]
:+1:

**Pull request merged**
