### PR TITLE
Add match-media store

### PR DESCRIPTION
**Pull request by synbot**
## Add match-media store

As done in other project(s).

### Acceptance Criteria
1. None

### Tasks
- Add store file
- That's it.

### Additional Notes
- Moved from synapsestudios/frontend-template#50

### CODE REVIEW

**Comment by paulstatezny** [comment]
:recycle:

**Comment by zpchavez** [comment]
:pray:

**Comment by zpchavez** [comment]
:recycle:

**Comment by canfie1d** [comment]
:+1:

**Pull request merged**
